 
---
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
metadata:
  name: eks-privyidcluster
  region: ap-southeast-1
  version: "1.18"
vpc:
  id: vpc-0ba75f63adcd21713
  subnets:
    public:
      subnet-public-a:
        id: subnet-05f17e46e6fe4567f
      subnet-pubic-b:
        id: subnet-0c7464a55d10647bc
    private:
      subnet-private-a:
        id: subnet-0277ce434e7dce8b2
      subnet-private-b:
        id: subnet-0b575f26bf5f7ace7
nodeGroups:
- name: spot-v2
  labels:
    role: spot
  minSize: 2
  maxSize: 3
  instancesDistribution:
    instanceTypes:
    - t2.medium
    onDemandBaseCapacity: 0
    onDemandPercentageAboveBaseCapacity: 80
  privateNetworking: true
  ssh:
    publicKeyName: Jumper-EC2
  subnets:
  - subnet-private-a
  - subnet-private-b
